---
- name: Install Flask and dependencies on EC2 instances
  hosts: flask
  become: yes

  tasks:
    - name: Update apt cache (for Ubuntu/Debian) or yum cache (for CentOS/RHEL)
      apt:
        update_cache: yes
      become: yes
      when: ansible_os_family == 'Debian'

    - name: Install Python and pip
      package:
        name: python3-pip
        state: present
      become: yes

    - name: Install Flask and required packages
      pip:
        name: "{{ item }}"
        state: present
      become: yes
      loop:
        - flask
        - flask-wtf
        - gunicorn

    - name: Enable firewall rule for Flask (e.g., port 5000)
      firewalld:
        port: 5000/tcp
        permanent: yes
        state: enabled
        immediate: yes
      become: yes
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: Enable firewall rule for Flask (e.g., port 5000)
      ufw:
        rule: allow
        port: '5000'
        state: enabled
      become: yes
      when: ansible_distribution == 'Ubuntu'
